### ISSUE TITLE
Not published on gh-pages

### ISSUE THREAD

**Issue by jGleitz** [kit-sdq/updatesite#1]
According to [Vitruv’s Getting Started wiki page](https://github.com/vitruv-tools/Vitruv/wiki/Getting-Started#Selecting_Required_Plugins) and [BuildUtilities/travis-ci/deploy.sh](https://github.com/kit-sdq/BuildUtilities/blob/master/travis-ci/deploy.sh), the contents of this repository should be published on GithHub Pages so users can use it as an Eclipse Update Site. [It is not](https://kit-sdq.github.io/updatesite/nightly/).

**Comment by HeikoKlare** [comment]
It is!? Your [link](https://kit-sdq.github.io/updatesite/nightly/) references our kit-sdq Updatesite. E.g., it contains a [compositeContent.xml](https://kit-sdq.github.io/updatesite/nightly/compositeContent.xml) and so on. Using it in Eclipse, it shows the deployed features. Can you give more details on what is not working correctly with the Updatesite?

**Comment by jGleitz** [comment]
I’m sorry, I was confused by the fact that the root link shows a 404 error (I never actually tried to use this update site, just stumbled across this). Sorry for wasting your time with an invalid issue!
